version: "3.9"
services:
  web:
    build: .
    working_dir: /home/node/app
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
    command: "npm start"
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=saved_tracks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Rosie123
    volumes:
      - ./db_script.sql.sql:/home/
      - lab-01-db:/var/lib/postgresql
volumes:
  lab-01-db: